version: "2"
services:

  referencedata:
    image: openlmis/referencedata
    links:
      - db
      - log
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx1536m'

  db:
    image: openlmis/postgres:12-debezium
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:3
    volumes:
      - '../logs/referencedata:/var/log'
